//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Registration_Birth_cirtificateEntities : DbContext
    {
        public Registration_Birth_cirtificateEntities()
            : base("name=Registration_Birth_cirtificateEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Children_information> Children_information { get; set; }
        public DbSet<Hosital_information> Hosital_information { get; set; }
        public DbSet<User> Users { get; set; }
        public object Groups { get; internal set; }
    }
}
